const ApiError = require('../utils/ApiError');

/**
 * AI Service
 * Abstraction layer for AI provider integration.
 * Currently supports OpenAI-compatible APIs.
 * Easily swappable to any other AI provider.
 */
class AIService {
    constructor() {
        this.apiKey = process.env.AI_API_KEY;
        this.apiUrl = process.env.AI_API_URL || 'https://api.openai.com/v1/chat/completions';
        this.model = process.env.AI_MODEL || 'gpt-3.5-turbo';
    }

    /**
     * Generate a professional summary for a resume
     * @param {Object} params - { jobTitle, experience, skills, tone }
     * @returns {String} generated summary
     */
    async generateSummary({ jobTitle, experience, skills, tone = 'professional' }) {
        if (!this.apiKey) {
            throw ApiError.internal('AI service is not configured. Set AI_API_KEY in environment.');
        }

        const prompt = this._buildSummaryPrompt({ jobTitle, experience, skills, tone });

        try {
            const response = await fetch(this.apiUrl, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${this.apiKey}`,
                },
                body: JSON.stringify({
                    model: this.model,
                    messages: [
                        {
                            role: 'system',
                            content:
                                'You are an expert resume writer. Generate concise, impactful professional summaries tailored for the given role. Keep it between 3-5 sentences.',
                        },
                        {
                            role: 'user',
                            content: prompt,
                        },
                    ],
                    max_tokens: 300,
                    temperature: 0.7,
                }),
            });

            if (!response.ok) {
                const errorData = await response.json().catch(() => ({}));
                throw new Error(errorData.error?.message || `AI API error: ${response.status}`);
            }

            const data = await response.json();
            const summary = data.choices?.[0]?.message?.content?.trim();

            if (!summary) {
                throw new Error('No summary generated by AI');
            }

            return summary;
        } catch (error) {
            if (error instanceof ApiError) throw error;
            console.error('AI Service Error:', error.message);
            throw ApiError.internal(`AI generation failed: ${error.message}`);
        }
    }

    /**
     * Build the prompt for summary generation
     * @private
     */
    _buildSummaryPrompt({ jobTitle, experience, skills, tone }) {
        let prompt = `Generate a ${tone} resume summary for a ${jobTitle}`;

        if (experience && experience.length > 0) {
            const expSummary = experience
                .map((exp) => `${exp.position} at ${exp.company}`)
                .join(', ');
            prompt += ` with experience as: ${expSummary}`;
        }

        if (skills && skills.length > 0) {
            const skillNames = skills.map((s) => (typeof s === 'string' ? s : s.name)).join(', ');
            prompt += `. Key skills: ${skillNames}`;
        }

        prompt += '. Make it compelling and ATS-friendly.';
        return prompt;
    }
}

module.exports = new AIService();
